stages:
  - test
  - lint
  - format
  - type_check

lint:
  stage: lint
  image: python:3.11
  script:
    - pip install ruff
    - ruff check .

format:
  stage: format
  image: python:3.11
  script:
    - pip install black
    - black --check .

type_check:
  stage: type_check
  image: python:3.11
  script:
    - pip install mypy
    - mypy .

test:
  stage: test
  image: python:3.11
  script:
    - pip install pytest pytest-cov
    - pytest
